AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - Gemfile
    - Rakefile
    - Guardfile
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
